Description: "Create a standard S3 bucket which can be used to upload cf stacks"
Parameters:
  ProductionStage:
    Description: Set application stage to dev, test or prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  ApplicationName:
    Description: Name of the application. Should be unique in AWS environment
    Type: String

Resources:
  CFDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ApplicationName}-cf-deployment-${ProductionStage}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  CFDeploymentBucketName:
    Description: The deployment bucket name
    Value: !Ref CFDeploymentBucket
    Export:
      Name: !Sub ${ApplicationName}-cf-bucket-${ProductionStage}